/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cgfay_media_MusicDecoder */

#ifndef _Included_com_cgfay_media_MusicDecoder
#define _Included_com_cgfay_media_MusicDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    init
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_com_cgfay_media_MusicDecoder_init
  (JNIEnv *, jobject, jfloat, jint);

/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    readSamples
 * Signature: ([SI[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_cgfay_media_MusicDecoder_readSamples
  (JNIEnv *, jobject, jshortArray, jint, jintArray, jintArray);

/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    setAccompanyVolume
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_cgfay_media_MusicDecoder_setAccompanyVolume
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    startAccompany
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cgfay_media_MusicDecoder_startAccompany
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    pauseAccompany
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cgfay_media_MusicDecoder_pauseAccompany
  (JNIEnv *, jobject);

/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    resumeAccompany
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cgfay_media_MusicDecoder_resumeAccompany
  (JNIEnv *, jobject);
/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    seek
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cgfay_media_MusicDecoder_seek
        (JNIEnv *, jobject, jfloat seconds);
/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    stopAccompany
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cgfay_media_MusicDecoder_stopAccompany
  (JNIEnv *, jobject);

/*
 * Class:     com_cgfay_media_MusicDecoder
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cgfay_media_MusicDecoder_destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
